---
title: "C183 - Project 5"
output: pdf_document
---

```{r}
#Read the data:
stock <- read.csv("stockData.csv", sep=",", header=TRUE)
stock <- stock[-2:-1]

# Convert non-numeric columns to numeric
data <- apply(stock, 2, function(x) as.numeric(as.character(x)))


# Compute the mean returns, excluding missing values
R_ibar <- as.matrix(mean(data, na.rm = TRUE))
R_ibar

#Compute the variance-covariance matrix:
var_covar <- cov(data)
head(var_covar)

#Compute the inverse of the variance-covariance matrix:
var_covar_inv <- solve(var_covar)
head(var_covar_inv)

#Create the vector R:
Rf <- 0.002
R <- R_ibar-Rf

#z <- var_covar_inv %*% R
#x <- z/sum(z)
#R_Gbar <- t(x) %*% R_ibar
#var_G <- t(x) %*% var_covar %*% x
#sd_G <- var_G^0.5
#slope <- (R_Gbar-Rf)/(sd_G)


```

```{r}
stock <- read.csv("stockData.csv", sep=",", header=TRUE)
stock <- stock[,-1]


p1 <- stock[1:61,]
p2 <- stock[61:99,]


r1 <- (p1[-1,3:ncol(p1)]-p1[-nrow(p1),3:ncol(p1)])/p1[-nrow(p1),3:ncol(p1)]
r2 <- (p2[-1,3:ncol(p2)]-p2[-nrow(p2),3:ncol(p2)])/p2[-nrow(p2),3:ncol(p2)]


#Compute the variance covariance matrix of the returns for each period:
covmat1 <- var(r1)
covmat2 <- var(r2)

#Compute the betas in each period:
beta1 <- covmat1[1,-1] / covmat1[1,1]
beta2 <- covmat2[1,-1] / covmat2[1,1]

#Here is the plot of the betas in period 2 against the betas in perod 1:
plot(beta1, beta2)

#Correlation between the betas in the two periods:
cor(beta1, beta2)


#Adjust betas using the Blume's technique:
q1 <- lm(beta2 ~ beta1)


beta3adj_blume <- q1$coef[1] + q1$coef[2]*beta2
```

```{r}
p3 <- stock[61:99,]
r3 <- (p3[-1,3:ncol(p3)]-p3[-nrow(p3),3:ncol(p3)])/p3[-nrow(p3),3:ncol(p3)]

covmat3 <- var(r3)
beta3 <- covmat3[1,-1] / covmat3[1,1]

#Vasicek's method:
beta2 <- rep(0,60)

alpha2 <- rep(0,60)

sigma_e2 <- rep(0,60)

var_beta2 <- rep(0,60)

for (i in 1:59) {
  q <- lm(data = r1, formula = unlist(r1[i + 1,]) ~ unlist(r1[ 1,]))
  beta2[i] <- q$coefficients[2]
  alpha2[i] <- q$coefficients[1]
  sigma_e2[i] <- summary(q)$sigma^2
  var_beta2[i] <- vcov(q)[2, 2]
}


#Adjusting the betas using the Vasicek's technique:
beta3adj_vasicek <- var_beta2*mean(beta2)/(var(beta2)+var_beta2) + 
var(beta2)*beta2/(var(beta2)+var_beta2)

PRESS3 <- sum((beta3adj_vasicek-beta3)^2) / 60

cbind(beta3, beta3adj_vasicek)



```