---
title: "C183 - Project 6"
output: pdf_document
---

```{r}
library(dplyr)
library(ggplot2)
stock <- read.csv("stockData.csv", sep=",", header=TRUE)
returns <- (stock[-1,3:ncol(stock)]-stock[-nrow(stock),3:ncol(stock)])/stock[-nrow(stock),3:ncol(stock)]
market <- var(returns$X.GSPC)

stock_names <- colnames(returns)
stock_names <- stock_names[2:length(stock_names)]


data <- data.frame()
n <- nrow(returns)


for(i in stock_names){
  
t <- paste(i, 'X.GSPC', sep = ' ~ ')
model <- lm(t, data = returns)
co <- as.numeric(model$coefficients)
var <- sum(model$residuals^2) / (n-2)
data <- rbind(data, c(co, var))

}


colnames(data) <- c('alpha', 'beta', 'sigma')
sigma <- var(returns$X.GSPC)
rownames(data) <- stock_names

data %>% arrange(desc(beta))



m1 <- diag(data$sigma)
b <- as.matrix(data$beta)


m2 <- sigma * (b %*% t(b))
total <- m1 + m2

colnames(total) <- stock_names
rownames(total) <- stock_names



stock2 <- read.csv("stockData.csv", sep=",", header=TRUE)[1:60,]
data2 <- (stock2[-1,4:ncol(stock2)]-stock2[-nrow(stock2),4:ncol(stock2)])/stock2[-nrow(stock2),4:ncol(stock2)]

r <- as.matrix(colMeans(data2))
sigma_mat <- cov(data2)


i_m <- matrix(rep(1,30), 30, 1)
A <- as.numeric(t(r) %*% solve(sigma_mat) %*% i_m)
B <- as.numeric(t(r) %*% solve(sigma_mat) %*% r)
C <- as.numeric(t(i_m) %*% solve(sigma_mat) %*% i_m)
D <- B*C - A^2

sigmas <- exp(seq(-2, -1, 0.0001))
sigmas_S <- exp(seq(-3, -1, 0.0001))
e1 <- A/C + sqrt(D * (C * sigmas^2 - 1)) / C
e2 <- A/C - sqrt(D * (C * sigmas^2 - 1)) / C

# SIM method
A_S <- as.numeric(t(r) %*% solve(total) %*% i_m)
B_S <- as.numeric(t(r) %*% solve(total) %*% r)
C_S <- as.numeric(t(i_m) %*% solve(total) %*% i_m)
D_S <- B_S*C_S - A_S^2

e1_S <- A_S/C_S + sqrt(D_S * (C_S * sigmas_S^2 - 1)) / C_S
e2_S <- A_S/C_S - sqrt(D_S * (C_S * sigmas_S^2 - 1)) / C_S


```

```{r}
library(dplyr)
r_i <- apply(returns,2,mean)[2:31]
data <- data %>% mutate(R_i = r_i) %>% mutate(stock_n = 1:30)
data_new <- data
R_f <- 0.005

data <- data %>% mutate(excess_beta = (R_i - R_f)/beta) %>%  mutate(beta_var = beta^2/sigma) %>% 
mutate(C_star_num = (R_i - R_f) * beta / sigma) #(R_i - R_f) * beta / sigmaˆ2
sort_data <- data %>% arrange(desc(excess_beta))

sort_data <- sort_data %>% mutate(sum_cstar = cumsum(C_star_num)) %>% mutate(sumbeta_var = cumsum(beta_var)) %>% mutate(C_i = market * sum_cstar / (1 + market * sumbeta_var))

C_star <- sort_data$C_i[nrow(sort_data)] #Cˆ* = last C_i

sort_data



x_market <- mean(returns$X.GSPC)
sd_market <- sd(returns$X.GSPC)
sd_stock <- sqrt(diag(sigma_mat))

g <- ggplot() + geom_line(aes(x = sigmas, y = e1, color = 'Frontier Historical Modle E1')) +
geom_line(aes(x = sigmas, y = e2, color = 'Frontier Historical Model E2')) +
geom_line(aes(x = sigmas_S, y = e1_S, color = 'Frontier SIM Model E1_S')) +
geom_line(aes(x = sigmas_S, y = e2_S, color = 'Frontier SIM Model E2_S')) +
geom_point(aes(x = sd_stock, y = r, color = 'Stocks')) +
geom_point(aes(x = sd_market, y = x_market, color = 'SPY'), size = 2) +
xlab('Risk') +
ylab('Expected Return') +
xlim(0, 0.5)

g

sort_data <- sort_data %>% mutate(zi_short = (beta / sigma) * (excess_beta))  %>%  mutate(x_short = zi_short / sum(zi_short))
                                                                              
r_short <- sum(sort_data$R_i * sort_data$x_short)
total_2 <- sort_data %>% arrange(stock_n)
sd_short <- sqrt(as.numeric(t(total_2$x_short) %*% total %*% total_2$x_short))

sort_data_2 <- sort_data %>% filter(excess_beta > C_i)
C_star_short <- sort_data_2$C_i[nrow(sort_data_2)]

sort_data_2 <- sort_data_2 %>% mutate(z_i = (beta/sigma) * (excess_beta - C_star_short)) %>% mutate(x_i = z_i/sum(z_i))
                                                            
stocks_2 <- rownames(sort_data_2)
Ri_2 <- r[stocks_2,]
vcov_2 <- total[stocks_2, stocks_2]
r_xshort <- sum(Ri_2 * sort_data_2$x_i)
sd_xshort <- sqrt(as.numeric(t(sort_data_2$x_i) %*% vcov_2 %*% sort_data_2$x_i))


g <- g + 
  geom_point(aes(x = sd_short, y = r_short, color = 'SIM Yes Short')) +
  geom_point(aes(x = sd_xshort, y = r_xshort, color = 'SIM No Short'))

g

total_2$x_short
sort_data_2$x_i


R_f <- 0.005
n <- 30

return_c <- returns[,2:31]
corr_mat <- cor(return_c)

rho = (sum(corr_mat) - n)/(n * (n-1))
sigma_i <- apply(returns,2,sd)[2:31]

results_c <- data_new %>% mutate(sigma_i = sigma_i) %>% mutate(return_sd = (R_i - R_f)/sigma_i) %>% arrange(desc(return_sd)) %>% mutate(rank = 1:30) %>% mutate(rho = rho/(1 + (rank - 1) * rho)) %>%
mutate(cum_excess = cumsum(return_sd)) %>% mutate(C_i = rho * cum_excess)

results_c
```
