---
title: "C183 - Project 4"
output: pdf_document
---

```{r}
library(dplyr)
library(ggplot2)

stock <- read.csv("stockData.csv", sep=",", header=TRUE)
returns <- (stock[-1,3:ncol(stock)]-stock[-nrow(stock),3:ncol(stock)])/stock[-nrow(stock),3:ncol(stock)]

stock_names <- colnames(returns)
stock_names <- stock_names[2:length(stock_names)]


data <- data.frame()
n <- nrow(returns)


for(i in stock_names){
  
t <- paste(i, 'X.GSPC', sep = ' ~ ')
model <- lm(t, data = returns)
co <- as.numeric(model$coefficients)
var <- sum(model$residuals^2) / (n-2)
data <- rbind(data, c(co, var))

}


colnames(data) <- c('alpha', 'beta', 'sigma')
sigma <- var(returns$X.GSPC)
rownames(data) <- stock_names

data %>% arrange(desc(beta))



m1 <- diag(data$sigma)
b <- as.matrix(data$beta)


m2 <- sigma * (b %*% t(b))
total <- m1 + m2

colnames(total) <- stock_names
rownames(total) <- stock_names

```

```{r}

stock2 <- read.csv("stockData.csv", sep=",", header=TRUE)[1:60,]
data2 <- (stock2[-1,4:ncol(stock2)]-stock2[-nrow(stock2),4:ncol(stock2)])/stock2[-nrow(stock2),4:ncol(stock2)]

r <- as.matrix(colMeans(data2))
sigma_mat <- cov(data2)


i_m <- matrix(rep(1,30), 30, 1)
A <- as.numeric(t(r) %*% solve(sigma_mat) %*% i_m)
B <- as.numeric(t(r) %*% solve(sigma_mat) %*% r)
C <- as.numeric(t(i_m) %*% solve(sigma_mat) %*% i_m)
D <- B*C - A^2

sigmas <- exp(seq(-2, -1, 0.0001))
sigmas_S <- exp(seq(-3, -1, 0.0001))
e1 <- A/C + sqrt(D * (C * sigmas^2 - 1)) / C
e2 <- A/C - sqrt(D * (C * sigmas^2 - 1)) / C

# SIM method
A_S <- as.numeric(t(r) %*% solve(total) %*% i_m)
B_S <- as.numeric(t(r) %*% solve(total) %*% r)
C_S <- as.numeric(t(i_m) %*% solve(total) %*% i_m)
D_S <- B_S*C_S - A_S^2

e1_S <- A_S/C_S + sqrt(D_S * (C_S * sigmas_S^2 - 1)) / C_S
e2_S <- A_S/C_S - sqrt(D_S * (C_S * sigmas_S^2 - 1)) / C_S


ER <- ggplot() + geom_line(aes(x = sigmas, y = e1, color = 'Historical model')) +
  
geom_line(aes(x = sigmas, y = e2, color = 'Historical model')) +
geom_line(aes(x = sigmas_S, y = e1_S, color = 'SIM model')) +
geom_line(aes(x = sigmas_S, y = e2_S, color = 'SIM model')) +
xlab('Risk') +
ylab('Expected Return') +
xlim(0.05, 0.5)
ER
```
